import type { AssessmentFormData } from "./schema";

// Local type — matches the identical local type in app/results/page.tsx (structural compatibility)
type StoredSubmission = {
  id: string;
  submittedAt: string;
  data: AssessmentFormData;
};

export const DEMO_SUBMISSION: StoredSubmission = {
  id: "demo",
  submittedAt: new Date().toISOString(),
  data: {
    companyName: "Acme Financial Ltd",
    industry: "financial",
    companySize: "51-200",
    regulatedEntity: true,
    regulator: "fca",
    purpose: "PI insurance renewal preparation",
    systemName: "Credit Scoring Engine v2",
    aiUseCase:
      "Scores consumer credit applications using income, credit history, and open banking data. Produces a recommend/decline output passed to an underwriter for final decision.",
    aiMaturity: "production",
    deploymentType: "customer",
    usersCount: "12000",
    frequencyOfUse: "daily",
    criticality: "customer",
    foundationModelSource: "proprietary",
    modelHosting: "vendor-hosted",
    retrainingFrequency: "quarterly",
    shadowAiDetection: "",
    thirdPartyVendors: "Experian, open banking provider",
    aiCapabilities: ["classification", "scoring"],
    decisionAuthority: "partial",
    financialImpactTier: "100k_to_1m",
    dataSensitivity: "sensitive",
    dataVolume: "50000",
    thirdPartyData: true,
    systematicRisk: "batch",
    mttd: "1_to_24_hours",
    explainabilityType: "interpretable",
    humanIntervention: "post-audit",
    biasTesting: ["Unsure"],
    modelDocs: ["None"],
    dataTypes: ["financial", "personal"],
    regulations: ["FCA Consumer Duty"],
    existingOversight: "periodic",
    incidentHistory: "none",
    documentedProcess: false,
    hasDpo: true,
    auditTrailCompleteness: "input-output",
    externalVerification: "none",
    changeManagement: "peer-review",
    trainingFrequency: "annually",
    monitoringHallucination: false,
    killSwitch: "manual-slow",
    incidentResponse: "",
    monitoring: ["None"],
    budget: "",
    supplyChain: "",
    hasModelCards: false,
    modelCardsUrl: "",
    hasExternalAudit: false,
    externalAuditType: undefined,
    auditReportUrl: "",
    hasRedTeaming: false,
    redTeamingDate: "",
    redTeamingReportUrl: "",
    apiEndpoint: "",
    apiAccessible: false,
    aiCoverageCheck: "uncertain",
    consumerRedress: "in-progress",
    vulnerableCustomerHandling: "partial",
    consumerExplainability: "on-request",
    independentValidation: "none",
    smfAccountability: false,
    formalAiPolicy: "in-progress",
    incidentResponsePlan: false,
    additionalContext: "",
  },
};
